Reason: small bug with roi generation

diff --git a/main b/main
--- a/main
+++ b/main
@@ -28,15 +28,15 @@ fi
 # cleanup
 mkdir -p track
 
-if [ -f track.tck ]; then
-	mv ./track.tck ./track/
-	mkdir ./wmc ./wmc/tracts/
-	mv ./output.mat ./wmc/classification.mat
-	mv ./tracts/* ./wmc/tracts/
-	mv ./output_fibercounts.txt ./wmc/
-	rm -rf ./tmpSubj ./*.nii.gz* ./*.mif* ./tracts ./bin ./logs
-	exit 0;
-else
-	echo "tracking failed"
-	exit 1;
-fi
+#if [ -f track.tck ]; then
+#	mv ./track.tck ./track/
+#	mkdir ./wmc ./wmc/tracts/
+#	mv ./output.mat ./wmc/classification.mat
+#	mv ./tracts/* ./wmc/tracts/
+#	mv ./output_fibercounts.txt ./wmc/
+#	rm -rf ./tmpSubj ./*.nii.gz* ./*.mif* ./tracts ./bin ./logs
+#	exit 0;
+#else
+#	echo "tracking failed"
+#	exit 1;
+#fi
