Reason: minor changes

diff --git a/main b/main
--- a/main
+++ b/main
@@ -26,16 +26,16 @@ if [ ! -f track.tck ]; then
 fi
 
 # cleanup
-mkdir -p track
-
-if [ -f track.tck ]; then
-	mv track.tck ./track/
-	mv output.mat ./wmc/classification.mat
-	mv tracts ./wmc/
-	mv output_fibercounts.txt ./wmc/
-	rm tmpSubj *.nii.gz* *.mif*
-	exit 0;
-else
-	echo "tracking failed"
-	exit 1;
-fi
+#mkdir -p track
+#
+#if [ -f track.tck ]; then
+#	mv track.tck ./track/
+#	mv output.mat ./wmc/classification.mat
+#	mv tracts ./wmc/
+#	mv output_fibercounts.txt ./wmc/
+#	rm tmpSubj *.nii.gz* *.mif*
+#	exit 0;
+#else
+#	echo "tracking failed"
+#	exit 1;
+#fi
